# action.yml
name: 'PowerShell Hello World'
description: 'PowerShell Hello World'
branding:
  icon : alert-circle
  color: blue
inputs:
  variable1:
    description: 'Variable 1'
    required: false
    default: 'Hello World'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - ${{ inputs.variable1 }}