# action.yml
name: 'PowerShell Hello World'
description: 'PowerShell Hello World'
branding:
  icon : alert-circle
  color: blue
inputs:
  variable1:
    description: 'Variable 1'
    required: false
    default: 'value 1'
  variable2:
    description: 'Variable 2'
    required: false
    default: 'value 2'
  variable3:
    description: 'Variable 3'
    required: false
  variable4:
    description: 'Variable 4'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - '${{ inputs.variable1 }}' 
    - '${{ inputs.variable2 }}' 
    - '${{ inputs.variable3 }}'
    - '${{ inputs.variable4 }}'