name: Load available actions
on: 
  push: 

  workflow_dispatch:
    
jobs:
  load-all-used-actions:
    runs-on: ubuntu-latest
    steps: 
      - uses: rajbos/github-action-load-available-actions@typescript
        name: Load used actions
        with: 
          PAT: ${{ secrets.PAT }}
        id: load-actions
        
      - shell: pwsh        
        run: |
         Write-Host "Found actions [${{ steps.load-actions.outputs.actions }}]"
         $content = ${{ steps.load-actions.outputs.actions }}
         New-Item -Path 'actions.json' -Value $content -Force | Out-Null
            
      - name: Upload result file as artefact
        uses: actions/upload-artifact@v2
        with: 
          name: actions
          path: actions.json
