on: 
  push: 

  workflow_dispatch:
    
jobs:
  load-all-used-actions:
    runs-on: ubuntu-latest
    steps: 
      - uses: rajbos/github-action-load-used-actions@main
        name: Load used actions
        with: 
          PAT: ${{ secrets.GITHUB_TOKEN }}
        id: load-actions
      - shell: pwsh        
        run: |
         Write-Host "Found test [${{ steps.load-actions.outputs.test }}]" 
         Write-Host "Found actions [${{ steps.load-actions.outputs.actions }}]"