name: File upload

on: 
  push: 

  workflow_dispatch:
    
jobs:
  file-upload:
    runs-on: ubuntu-latest
    steps: 

    - name: Create file
      run: |
        echo "this is the file contents" > test.txt
        echo "1: ${{ github.GITHUB_REPOSITORY }}" || true
        echo "2: ${{ env.GITHUB_REPOSITORY }}" || true

    - uses: rajbos/github-upload-action@master
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
        file-path: test.txt
        username: x
        repo: ${{ github.GITHUB_REPOSITORY }}