name: File upload

on: 
  push: 

  workflow_dispatch:
    
jobs:
  file-upload:
    runs-on: ubuntu-latest
    steps: 

    - name: Create file
      run: |
        echo "this is the file contents" > test.txt

    - uses: rajbos/github-upload-action@owner-param
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
        file-path: test.txt
        owner: rajbos
        repo: actions-testing-grounds
        remote-dir: test
        branch-name: not-existing-branch