name: File upload

on: 
  push: 

  workflow_dispatch:
    
jobs:
  file-upload:
    runs-on: ubuntu-latest
    steps: 

    - name: Create file
      run: |
        echo "this is the file contents" > test.txt

    - uses: rajbos/github-upload-action@push-to-branch
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
        file-path: test.txt
        username: x
        repo: ${{ github.repository }}
        remote-dir: test
        branch-name: not-existing-branch